# .github/workflows/ci.yml

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
     
# .github/workflows/ci.yml

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job_for_frontend:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[frontend]')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci frontend

      - name: Run tests
        run: npm test frontend
 
      - name: Build project
        run: npm run build frontend


  job_for_backend:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[backend]')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci backend

      - name: Run tests
        run: npm test backend
 
      - name: Build project
        run: npm run build backend
